[features]
seeds = false
[programs.localnet]
solana_svelte_voting = "B2U6Lz4j6guHFf5DmXRgy5SXkuZnucfhp74J1Vm5YRQv"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/silvestrevivo/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
